apiVersion: v1
kind: ReplicationController
metadata: 
  name: api-v1.0.10
spec: 
  replicas: 1
  selector: 
    name: api
    version: v1.0.10
  template: 
    metadata: 
      labels: 
        name: api
        version: v1.0.10
    spec: 
      containers: 
        - 
          image: "gcr.io/slacker-157712/api:v1.0.10"
          name: api
          ports: 
            - 
              containerPort: 3000
