apiVersion: v1
kind: ReplicationController
metadata: 
  name: api-{{tag}}
spec: 
  replicas: 3
  selector: 
    name: api
    version: {{tag}}
  template: 
    metadata: 
      labels: 
        name: api
        version: {{tag}}
    spec: 
      containers: 
        - 
          image: "gcr.io/docker-containers-156417/api:{{tag}}"
          name: api
          ports: 
            - 
              containerPort: 3000