apiVersion: v1
kind: ReplicationController
metadata: 
  name: api-v1
spec: 
  replicas: 3
  selector: 
    name: api
    version: v1
  template: 
    metadata: 
      labels: 
        name: api
        version: v1
    spec: 
      containers: 
        - 
          image: "gcr.io/docker-containers-156417/api:v1"
          name: api
          ports: 
            - 
              containerPort: 3000
