apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: api
  name: api
spec: 
  type: LoadBalancer
  ports: 
    - 
      port: 80
      protocol: TCP
      targetPort: 3000
  selector: 
    name: api